INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (false,'2001-11-01','11 Ben Nghe','admin123@gmail.com','admin1','admin123','admin','0938472726',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (true,'2002-10-21','08 Nguyen Binh Khiem, Quang Ngai','quangtin1@gmail.com','manager1','manager123','manager','0395115975',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (true,'2003-10-23','2123 Le Viet Luong','tintq2@gmail.com','tintq2','123456a~','customer','0938472725',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (true,'2002-02-02','DakLak','thiencm02@gmail.com','thiencm02Aa','Tian1a)','manager','0938472720',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (true,'2002-04-07','04 Le Van Viet','cuong@gmail.com','cuong3Que','chrissTrinha123^','customer','0938472721',1);
INSERT INTO user(gender,birthday,address,email,name,password,role,phone,status)
VALUES (false,'2000-09-02','113 Quang Trung, Da Nang','vanh khuyen43@gmail.com','Vanhkh43','Bon3@!.','customer','0395117976',1);


INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES ('Cẩm Nang Xây Dựng','Thiết Kế Phòng Khách Tivi Treo Tường Hiện Đại Đẹp Không Góc Chết','hihi',2,'2023-02-05',null);
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES ('Cẩm Nang Xây Dựng','11+ Mẫu Phòng Bếp Nhà Ống','hihi',3,'2023-02-05',null);
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES ('Cẩm Nang Xây Dựng','30+ Mẫu Thiết Kế Phòng Khách Có Cầu Thang Dọc Không Thể Bỏ Lỡ','hihi',4,'2024-02-20',null);
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES ('Thiết Kế Kiến Trúc','Quy Trình Thiết Kế Nhà Trọn Gói','hihi',5,'2023-02-05',null);
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES ('Thiết Kế Kiến Trúc','TOP 25 Mẫu Nhà Phố Có Garage Đẹp Mới Nhất','hihi',2,'2023-02-05',null);
INSERT INTO blog(blog_type,blog_name,blog_content,user_id,create_day,img_path) VALUES ('Thiết Kế Kiến Trúc','Bật Mí Xu Hướng Thiết Kế Nội Thất Phòng Khách Hiện Đại, Sang Trọng','hihi',4,'2023-02-05',null);

INSERT INTO item_type(item_type_name, status) VALUES ('Mái',1);
INSERT INTO item_type(item_type_name, status) VALUES ('Hầm',1);
INSERT INTO item_type(item_type_name, status) VALUES ('Tầng',1);
INSERT INTO item_type(item_type_name, status) VALUES ('Móng',1);
INSERT INTO item_type(item_type_name, status) VALUES ('Loại Nhà',1);

INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (1,'Mái Tôn ',1020000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (1,'Mái BTCT ',1360000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (1,'Mái BTCT Dán Ngói ',3400000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (1,'Mái Kèo Thép Lợp Ngói ',1450000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (1,'Xà Gỗ Lợp Ngói ',2380000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (2,'Không Hầm ',0,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (2,'Độ sâu 1.0 – 1.3 ',5100000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (2,'Độ sâu 1.3 – 1.7 ',5780000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (2,'Độ sâu 1.7 – 2.0 ',6800000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (2,'Độ sâu > 2.0 ',8500000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (3,'Tầng 1 ',3400000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (3,'Tầng 2 ',3400000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (3,'Tầng 3 ',3400000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (3,'Tầng 4 ',3400000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (3,'Tầng 5 ',3400000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (3,'Tầng Thượng ',3400000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (4,'Móng đơn ',960000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (4,'Móng băng ',2080000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (4,'Móng đài cọc ',1600000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (5,'Nhà Phố ',3400000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (5,'Biệt Thự ',3800000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (5,'Biệt Thự Cổ Điển ',4500000,1);
INSERT INTO item(item_type_id,item_name,price_item, status) VALUES (5,'Nhà Cấp 4 ',2400000,1);

INSERT INTO material_type(type_name, status) VALUES ('Sắt Thép',1);
INSERT INTO material_type(type_name, status) VALUES ('Cát Xây Dựng',1);
INSERT INTO material_type(type_name, status) VALUES ('Xi Măng Xây Dựng',1);
INSERT INTO material_type(type_name, status) VALUES ('Gạch Tuynel Xây Dựng',1);
INSERT INTO material_type(type_name, status) VALUES ('Gạch Ốp Nền, Tường',1);
INSERT INTO material_type(type_name, status) VALUES ('Đá Xây Dựng',1);
INSERT INTO material_type(type_name, status) VALUES ('Sơn Nước',1);
INSERT INTO material_type(type_name, status) VALUES ('Bột Trét',1);
INSERT INTO material_type(type_name, status) VALUES ('Cửa',1);
INSERT INTO material_type(type_name, status) VALUES ('Lan Can',1);
INSERT INTO material_type(type_name, status) VALUES ('Dây Điện, Dây Cáp',1);
INSERT INTO material_type(type_name, status) VALUES ('Ống Nước',1);
INSERT INTO material_type(type_name, status) VALUES ('Tôn',1);
INSERT INTO material_type(type_name, status) VALUES ('Ngói',1);

INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Hòa Phát Ø6, Ø8 ',1, 11000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Hòa Phát Ø10 ',1, 77995,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Hòa Phát Ø12 ',1, 110323,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Hòa Phát Ø14 ',1, 152208,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Hòa Phát Ø16 ',1, 199360,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Việt Nhật Ø10',1, 63582,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Việt Nhật Ø12',1, 73900,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Việt Nhật Ø14',1, 109900,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Việt Nhật Ø16',1, 150500,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Pomina Ø6, Ø8 ',1, 14500,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Pomina Ø10 ',1, 105773,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Pomina Ø12 ',1, 150655,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Pomina Ø14 ',1, 205322,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sắt Thép Pomina Ø16 ',1, 268105,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cát Vàng',2, 200000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cát Đen',2, 150000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cát Xây Tô',2, 120000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cát San Lấp',2, 90000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cát Bê Tông',2, 250000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Xi Măng SCG',3, 101000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Xi Măng Sông Gianh',3, 95000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Xi Măng Nghi Sơn',3, 89000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Xi Măng Hà Tiên',3, 85000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Xi Măng Hà Tiên Xây Tô',3, 76000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Xi Măng Vicem Hạ Long',3, 86000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Xi Măng INSEE',3, 87000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Xi Măng INSEE Xây Tô',3, 73000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Xi Măng FICO',3, 78000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Đặc Tuynel',4, 980,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Tuynel 2 Lỗ',4, 990,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Đặc Thạch Bàn',4, 1750,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Không Trát 2 Lỗ',4, 2900,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Không Trát 2 Lỗ Sẫm',4, 6200,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Đặc Không Trát Xám',4, 4100,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Đặc Không Trát Sẫm',4, 6200,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Đặc Không Trát Khổ Lớn',4, 26500,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Không Trát 3 Lỗ',4, 5600,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch 4 Lỗ Vuông ',4, 1220,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch 4 Lỗ Tròn ',4, 1320,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch 6 Lỗ Vuông ',4, 3500,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch 6 Lỗ Tròn',4, 3600,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Prime _30*60_8164 ',5, 167000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Prime _30*60_8632 ',5, 166000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Prime _30*60_8165 ',5, 187000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Prime_30*60_9455 ',5, 160000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Prime _30*60_8661 ',5, 195000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Prime _30*60_17315 ',5, 75000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Viglacera_30*60_3616A ',5, 210000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Viglacera_30*60_3676 ',5, 220000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Viglacera_30*60_3644A ',5, 225000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Viglacera_30*60_3623 ',5, 145000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Tường Viglacera_30*60_3604A ',5, 195000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền Prime_30*30_9612 ',5, 140000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền Prime_30*30_9473 ',5, 128000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền Prime_30*30_9603 ',5, 151000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền Prime_60*60_9669 ',5, 192000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền Prime_60*60_17026 ',5, 181000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền Prime_60*60_9864 ',5, 235000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền Prime_60*60_9509 ',5, 211000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền S_60*60_68017 ',5, 181000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền S_60*60_68035 ',5, 284000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền S_60*60_68030C ',5, 321000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Gạch Ốp Nền S_60*60_65001C ',5, 325000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Đá Xanh 1*2',6, 280000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Đá Xanh 0*4',6, 220000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Đá Xanh 4*6',6, 360000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Đá Xanh 5*7',6, 390000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Đá Đen 1*2',6, 260000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Đá Đen 4*6',6, 340000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Đá Mi Sàng',6, 220000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Đá Mi Bụi',6, 210000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Maxilite 5L',7, 415000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Maxilite 18L',7, 1405000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Maxilite HC 5L',7, 258000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Maxilite HC 18L',7, 878000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Maxilite Smooth 5L',7, 241000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Maxilite Smooth 18L',7, 801000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Dulux Inspire 5L',7, 551000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Dulux Inspire 18L',7, 1874000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Jotun Jotaplast',7, 851000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Jotun Majestic 5L',7, 873000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Jotun Majestic 15L',7, 2253000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Jotun Majestic Primer 5L',7, 483000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Sơn Jotun Majestic Primer 17L',7, 1548000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Bột Trét Homecote',8, 265000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Bột Trét Joton Nội Thất',8, 230000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Bột Trét Joton Ngoại Thất',8, 330000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Bột Trét Việt Mỹ Nội Thất',8, 110000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Bột Trét Việt Mỹ Ngoại Thất',8, 120000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Bột Trét Dulux Nội Thất',8, 310000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Bột Trét Dulux Ngoại Thất',8, 410000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Nhôm Xingfa Nhập Khẩu',9, 1650000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Nhôm Xingfa Trong Nước',9, 1550000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Nhôm Việt Pháp',9, 1100000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Gỗ HDF',9, 1990000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Gỗ HDF Veneer',9, 2450000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Gỗ HDF Melaminate',9, 2100000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Gỗ HDF Laminate',9, 2600000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Gỗ Vòm MDF',9, 1600000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Gỗ Vòm MDF Veneer',9, 1750000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Gỗ Vòm MDF Melaminate',9, 1950000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cửa Gỗ Vòm MDF Laminate',9, 2700000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Lan Can Kính Tempered 8mm Cường Lực',10, 510000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Lan Can Kính Tempered 12mm Cường Lực',10, 680000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Lan Can Sắt ',10, 550000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Lan Can Sắt Hộp',10, 850000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Lan Can Ban Công Inox201',10, 650000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Lan Can Ban Công Inox304',10, 920000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Lan Can Cầu Thang Inox201',10, 2200000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Lan Can Cầu Thang Inox304',10, 2700000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Lan Can Bậc Gỗ CămXe',10, 950000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cáp Ngầm CADIVI_50',11, 146500,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cáp Ngầm CADIVI_70',11, 163500,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cáp Ngầm CADIVI_95',11, 181500,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cáp Ngầm CADIVI_150',11, 218200,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cáp Ngầm CADIVI_240',11, 269700,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cáp Ngầm LS VINA_35',11, 230980,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cáp Ngầm LS VINA_50',11, 382300,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cáp Ngầm LS VINA_70',11, 436940,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cáp Điện SINO',11, 118000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Cáp Điện DAPHACO',11, 92270,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ống Nước Nhựa Tiền Phong 21',12, 9600,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ống Nước Nhựa Tiền Phong 27',12, 20700,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ống Nước Nhựa Tiền Phong 34',12, 34200,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ống Nước Nhựa Bình Minh 21',12, 12600,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ống Nước Nhựa Bình Minh 27',12, 15800,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ống Nước Nhựa Bình Minh 34',12, 21200,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ống Nước Nhựa Hoa Sen',12, 14600,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ống Nước Nhựa Dekko 21',12, 11495,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ống Nước Nhựa Dekko 27',12, 14960,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ống Nước Nhựa Dekko 34',12, 19495,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Tôn Việt Nhật',13, 69000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Tôn Đông Á',13, 93000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Tôn Hoa Sen',13, 95000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ngói Đất Nung',14, 26000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ngói Composite',14, 28000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ngói Màu(Ngói Xi Măng)',14, 39000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ngói Sóng',14, 15000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ngói Phẳng',14, 19000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ngói Thái Lan SCG',14, 20000,1);
INSERT INTO material(material_name,material_type_id,unit_price, status) VALUES ('Ngói Đồng Tâm',14, 24200,1);

INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Biệt Thự Thô',3500000, 0,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Biệt Thự Hoàn Thiện Hiện Đại',3800000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Biệt Thự Hoàn Thiện Cổ Điển',4000000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Biệt Thự Trọn Gói Hiện Đại',4300000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Biệt Thự Trọn Gói Cổ Điển',4600000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Phố Thô',2000000, 0,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Phố Hoàn Thiện 1',2200000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Phố Hoàn Thiện 2',2500000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Phố Trọn Gói 1',2700000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Phố Trọn Gói 2',3000000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Cấp 4 Thô',1500000, 0,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Cấp 4 Hoàn Thiện 1',1700000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Cấp 4 Hoàn Thiện 2',1900000, 1,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Cấp 4 Trọn Gói 1',2300000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Cấp 4 Trọn Gói 2',2500000, 2,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Nhà Xưởng',2500000, 0,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Phần Thô Quán Cafe',2200000, 0,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Phần Hoàn THiện Quán Cafe',2500000, 0,1);
INSERT INTO combo_building(combo_building_name,unit_price,type,status) VALUES ('Phần Trọn Gói Quán Cafe',3200000, 0,1);

INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,3);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,4);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,10);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,11);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,14);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,15);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,17);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,19);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,21);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,29);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,32);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,39);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,40);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,46);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,49);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,55);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,64);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,65);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,66);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,67);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,68);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,69);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,70);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,71);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,75);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,82);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,90);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,91);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,95);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,104);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,108);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,113);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,118);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,130);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,131);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (1,135);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,1);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,2);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,3);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,4);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,5);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,15);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,17);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,19);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,20);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,29);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,30);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,32);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,39);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,40);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,48);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,61);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,62);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,64);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,65);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,66);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,67);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,68);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,69);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,70);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,79);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,86);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,87);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,90);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,91);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,95);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,104);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,108);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,113);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,118);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,130);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,131);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,136);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,138);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (2,139);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,1);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,2);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,3);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,4);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,5);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,15);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,17);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,19);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,20);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,29);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,30);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,32);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,39);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,40);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,48);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,61);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,62);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,64);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,65);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,66);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,67);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,68);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,69);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,70);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,79);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,86);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,87);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,90);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,91);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,95);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,104);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,108);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,113);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,118);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,125);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,126);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,127);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,138);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,139);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (3,141);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,1);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,2);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,3);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,4);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,5);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,15);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,17);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,19);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,20);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,29);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,30);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,32);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,39);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,40);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,48);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,61);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,62);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,64);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,65);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,66);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,67);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,68);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,69);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,70);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,79);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,86);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,87);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,90);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,91);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,95);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,104);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,108);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,113);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,118);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,130);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,131);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,136);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,138);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (4,139);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,1);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,2);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,3);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,4);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,5);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,15);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,17);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,19);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,20);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,29);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,30);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,32);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,39);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,40);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,48);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,61);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,62);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,64);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,65);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,66);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,67);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,68);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,69);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,70);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,79);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,86);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,87);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,90);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,91);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,95);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,104);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,108);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,113);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,118);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,125);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,126);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,127);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,138);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,139);
INSERT INTO combo_detail(combo_building_id,material_id) VALUES (5,141);
